"""
URL Mapping for the recipe app
"""

from django.urls import (
    path,
    include,  # to inlude URLs by their URL Names
)

from rest_framework.routers import DefaultRouter 
# ^you can use this with an APIView to automatically create routes for all the different options available for that view

from recipe import views


router = DefaultRouter()
router.register('recipes', views.RecipeViewSet)  # Create a new endpoint `/api/recipe/recipes`
# ^Will also assign all of the different endpoints from our `RecipeViewSet` to that endpoint
# i.e. `RecipeViewSet` is going to have Auto-Generated URLs depending on the functionality that's enabled on the ViewSet
# Since we are using ModelViewSet in RecipeViewSet, it will support all available methods for CRUD (i.e. HTTP GET, POST, PUT, PATCH, DELETE)

router.register('tags', views.TagViewSet)


app_name = 'recipe'
urlpatterns = [
    path('', include(router.urls)),  # ^Include all of the URLs that were automatically generated by the `DefaultRouter`
]